mysql:
  platform: linux/x86_64
  image: mysql:8.0.26
  environment:
    MYSQL_ROOT_PASSWORD: root_password
    MYSQL_DATABASE: my_database
    MYSQL_USER: my_user
    MYSQL_PASSWORD: my_password
  volumes:
    - ./docker/mysql/data:/var/lib/mysql
  ports:
    - "3306:3306"